### Website : Codeshare

In [1]:
import numpy as np

In [2]:
a=np.array([21,546,87,86,279,256])
sum(a)


1275

In [3]:
b=a.copy() # it will create only copy

In [4]:
b

array([ 21, 546,  87,  86, 279, 256])

In [5]:
b=a.view() # it is the mirror image of a like if change the value of a it will also change in b
a[0]=84

In [6]:
b

array([ 84, 546,  87,  86, 279, 256])

In [7]:
a.dtype # returns data type

dtype('int32')

In [8]:
a.itemsize

4

In [9]:
a.reshape(2,3)

array([[ 84, 546,  87],
       [ 86, 279, 256]])

In [10]:
a.ndim # returns dimension

1

In [11]:
c=np.zeros(3) # creates an array of zeros
c

array([0., 0., 0.])

In [12]:
d=np.ones(5) # creates an array of ones
d

array([1., 1., 1., 1., 1.])