### Website : Codeshare

In [30]:
import numpy as np

In [31]:
a=np.array([21,546,87,86,279,256])
sum(a)


1275

In [32]:
b=a.copy() # it will create only copy

In [33]:
b

array([ 21, 546,  87,  86, 279, 256])

In [34]:
b=a.view() # it is the mirror image of an array,if change the value of a it will also change in b
a[0]=84

In [35]:
b

array([ 84, 546,  87,  86, 279, 256])

In [36]:
a.dtype # returns data type

dtype('int32')

In [37]:
a.itemsize

4

In [38]:
a.reshape(2,3)

array([[ 84, 546,  87],
       [ 86, 279, 256]])

In [39]:
a.ndim # returns dimension

1

In [40]:
c=np.zeros(3) # creates an array of zeros
c

array([0., 0., 0.])

In [41]:
d=np.ones(5) # creates an array of ones
d

array([1., 1., 1., 1., 1.])